M48
; DRILL file KiCad 10.0.0 date 2026-04-21T22:53:30
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-21T22:53:30+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X147.0Y-78.04
X150.0Y-78.04
T2
X113.0Y-102.0
X154.5Y-89.0
M30
